security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
    
    providers:
        database:
            entity:
                class: App\Entity\User
                property: email 
    
    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: /login 
            security: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
